### ISSUE TITLE
Pretty sure I got same subnet twice in a row?

### ISSUE THREAD

**Issue by max-b** [sudomesh/meshnode-database#2]
If you take a look at our "production" database right now, there should be two different entries right in a row for 100.64.4.0/26. When I "makenoded" the first one, there wasn't any sign that the database hadn't registered it.

**Comment by max-b** [comment]
Hmm I got assigned that address again..... I'll see if I can dig up those db credentials and/or go into the server to see if there are any obvious log errors.

**Comment by max-b** [comment]
Seems as though I was eventually assigned another address, but now I'm receiving that one again. Looking through the nodes db, it seems as though I was assigned the 100.64.4.0/26 4 times and so far I've been assigned 100.64.4.64/26 twice. I'll take a quick look to see if there's anything obvious.

**Comment by paidforby** [comment]
this is no longer an issue
